spring:
  shardingsphere:
    enabled: true # 是否启用sharding，不启用时使用datasource配置的数据源
    datasource:
      names: master,slave0 # 节点名称，多个时使用逗号隔开
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name:  com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/spring-boot-all?autoReconnect=true&failOverReadOnly=false&autoReconnectForPools=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: 123456
        # 以下为druid配置，可以共用datasource中的druid配置，需要覆盖时再重新配置
#        filters: stat,wall,logback
        initial-size: 10
        max-active: 50
        min-idle: 10
      slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/spring-boot-imp-admin?autoReconnect=true&failOverReadOnly=false&autoReconnectForPools=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: 123456
        # 以下为druid配置，可以共用datasource中的druid配置，需要覆盖时再重新配置
#        filters: stat,wall,logback
        initial-size: 10
        max-active: 50
        min-idle: 10
    rules:
      readwrite-splitting:
        load-balancers:
          round_robin:
            type: ROUND_ROBIN
        data-sources:
          readwrite_ds:
            static-strategy:
              write-data-source-name: master
              read-data-source-names: slave0
              load-balancer-name: round_robin
    mode:
      type: Standalone
      repository:
        type: File
        props:
          path: .shardingsphere
        overwrite: false
    props:
      sql-show: true